# These substitutions allow the end user to override certain values
substitutions:
  name: "axa-remote-pcb"
  friendly_name: "AXA Remote"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "AXA Remote 2.0 Window Opener"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # Define sub-devices
  devices:
    - id: axa_2
      name: "${friendly_name} 2"

external_components:
  - source: github://rrooggiieerr/esphome-axaremote@0.1.2
    components: [axaremote]
    refresh: never

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    id: ota_esphome

wifi:
  # Set up a wifi access point using the device name above
  ap:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

uart:
  - id: uart_axa1
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 19200
    stop_bits: 2
  - id: uart_axa2
    tx_pin: GPIO23
    rx_pin: GPIO22
    baud_rate: 19200
    stop_bits: 2

light:
  - platform: status_led
    id: _status_led
    pin:
      number: GPIO2
      inverted: False
      ignore_strapping_warning: True
    internal: True

sensor:
  - platform: adc
    id: brightness
    name: "Brightness"
    pin: GPIO33
    device_class: illuminance
    attenuation: auto
    update_interval: 10s
    unit_of_measurement: "%"
    icon: "mdi:brightness-5"
    accuracy_decimals: 1
    filters:
      # 0.075 V = 0%
      # 3.14853 V = 100%
      - lambda: return ((x - 0.075) / (3.14853 - 0.075)) * 100;
    disabled_by_default: True

binary_sensor:
  - platform: gpio
    id: boot_button
    pin:
      number: GPIO0
      mode:
        input: True
        pullup: True
      inverted: True
      ignore_strapping_warning: True
    internal: True
    filters:
      - delayed_on: 50ms 
    on_multi_click:
      - timing:
          - ON for 0.2s to 3s
          - OFF for 0.1s to 2s
          - ON for 0.2s to 3s
          - OFF for 0.1s to 2s
          - ON for at least 5s 
        then:
          - repeat: 
              count: 5
              then:
                - light.turn_on: _status_led
                - delay: 150ms
                - light.turn_off: _status_led
                - delay: 150ms
          - light.turn_on: _status_led
          - button.press: factory_reset_button

button:
  - platform: factory_reset
    id: factory_reset_button
    internal: True

cover:
  - platform: axaremote
    name: "Window 1"
    id: cover_axa1
    device_class: window
    uart_id: uart_axa1
    # close_duration: 50s
    auto_calibrate: True
  - platform: axaremote
    name: "Window 2"
    id: cover_axa2
    device_id: axa_2
    device_class: window
    uart_id: uart_axa2
    # close_duration: 50s
    auto_calibrate: True
